# NOTE: In our Jenkins CI MastodonAndroid/gradle/libs.versions.toml file is copied to modules/gradle/libs.versions.toml
# Thus if you need to build modules from command line you need to manually also copy the toml file allowing to Gradle to resolve dependencies correctly

[versions]
appcompat = "1.7.1"
androidGradlePlugin = "8.13.1"
kotlinGradlePlugin = "2.2.10"
material = "1.12.0"
gson = "2.13.1"
apacheCommons = "3.18.0"
jetbrainsAnnotations = "26.0.2-1"
junit = "4.13.2"
testRunner = "1.7.0"
androidxTestRules = "1.7.0"
testEspresso = "3.7.0"
kotlinxCoroutines = "1.10.2"
guava = "33.4.8-android"
constraintlayout = "2.2.1"
androidxCore = "1.17.0"
androidxLifecycle = "2.9.3"
androidxRecyclerview = "1.4.0"
androidxLegacy = "1.0.0"
androidxTestExtJunit = "1.3.0"
appCenterSdkVersion = "5.0.6"
mockitoCore = "5.19.0"
monitor = "1.8.0"
androidXmlRunListener = "0.3.1"
orchestrator = "1.6.1"
androidxAnnotation = "1.9.1"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
android-material = { module = "com.google.android.material:material", version.ref = "material" }
google-gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
apache-commons = { module = "org.apache.commons:commons-lang3", version.ref = "apacheCommons" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrainsAnnotations" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "testRunner" }
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "testEspresso" }
androidx-test-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "testEspresso" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
google-guava = { module = "com.google.guava:guava", version.ref = "guava" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidxRecyclerview" }
androidx-legacy = { module = "androidx.legacy:legacy-support-v4", version.ref = "androidxLegacy" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestExtJunit" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidxTestRules" }
microsoft-appcenter-analytics = { module = "com.microsoft.appcenter:appcenter-analytics", version.ref = "appCenterSdkVersion" }
microsoft-appcenter-crashes = { module = "com.microsoft.appcenter:appcenter-crashes", version.ref = "appCenterSdkVersion" }
mockito-android = { module = "org.mockito:mockito-android", version.ref = "mockitoCore" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
android-xml-run-listener = { module = "de.schroepf:android-xml-run-listener", version.ref = "androidXmlRunListener" }
androidx-orchestrator = { module = "androidx.test:orchestrator", version.ref = "orchestrator" }
androidx-monitor = { module = "androidx.test:monitor", version.ref = "monitor" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidxAnnotation" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinGradlePlugin" }